"use client";

import { useEffect, useState } from "react";
import { libraryBooks } from "./library-data";
import { ArrowUpRight, Bookmark, Check, ChevronRight, Home as HomeIcon, MoreHorizontal, Plus, Sparkles, Star } from "lucide-react";

type View = "home" | "book" | "recommendations";
const books = {
  mistborn: { title: "Mistborn: The Final Empire", author: "Brandon Sanderson", image: "https://covers.openlibrary.org/b/isbn/9780765311788-L.jpg", format: "Owned · Paperback" },
  babel: { title: "Babel", author: "R. F. Kuang", image: "https://covers.openlibrary.org/b/isbn/9780063021426-L.jpg", format: "Owned · Hardcover" },
  redRising: { title: "Red Rising", author: "Pierce Brown", image: "https://covers.openlibrary.org/b/isbn/9780345539786-L.jpg", format: "Owned · E-book" },
  will: { title: "The Will of the Many", author: "James Islington", image: "https://covers.openlibrary.org/b/isbn/9781982141189-L.jpg", format: "Wish list" },
  priory: { title: "The Priory of the Orange Tree", author: "Samantha Shannon", image: "https://covers.openlibrary.org/b/isbn/9781635570298-L.jpg", format: "Borrowed · Audiobook" },
  gatsby: { title: "The Great Gatsby", author: "F. Scott Fitzgerald", image: "https://covers.openlibrary.org/b/olid/OL782874M-L.jpg", format: "Wish list" },
};
type Book = typeof books.mistborn;
function Cover({ book, className = "" }: {book: Book; className?: string}) { return <img className={`book-cover ${className}`} src={book.image} alt={`Cover of ${book.title}`} />; }
function Nav({view,setView}:{view:View;setView:(v:View)=>void}) { return <header className="topbar"><button className="brand" onClick={()=>setView("home")}><span>l</span> Lumen</button><nav><button className={view==="home"?"active":""} onClick={()=>setView("home")}><HomeIcon size={16}/> My library</button><button className={view==="recommendations"?"active":""} onClick={()=>setView("recommendations")}><Sparkles size={16}/> For you</button></nav><button className="avatar" aria-label="Open profile">DA</button></header>; }
function MiniBook({book,onClick}:{book:Book;onClick?:()=>void}) { return <button className="mini-book" onClick={onClick}><Cover book={book}/><span>{book.title}</span><small>{book.author}</small><em>{book.format}</em></button>; }
function HomeView({setView}:{setView:(v:View)=>void}) { const ownedBooks = libraryBooks.filter((book) => book.status === "owned").length; const wishListBooks = libraryBooks.filter((book) => book.status === "wishlist").length; return <main className="page-grid"><section className="content library-home"><div className="eyebrow"><span/> My personal library</div><div className="home-heading"><div><h1>Your library, all in one place.</h1><div className="collection-summary" aria-label={`${libraryBooks.length} books: ${ownedBooks} owned and ${wishListBooks} on your wish list`}><span><b>{libraryBooks.length}</b><small>books</small></span><span><b>{ownedBooks}</b><small>owned</small></span><span><b>{wishListBooks}</b><small>wish list</small></span></div></div><button className="quiet-button"><Plus size={17}/> Add a book</button></div><section className="shelf-section"><div className="section-title"><div><span className="section-kicker">All your formats, together</span><h2>Your collection</h2></div><button>View library <ChevronRight size={15}/></button></div><div className="book-row"><MiniBook book={books.mistborn} onClick={()=>setView("book")}/><MiniBook book={books.babel}/><MiniBook book={books.priory}/><MiniBook book={books.redRising}/><div className="more-card"><span>{libraryBooks.length - 4}</span><small>more books<br/>in your library</small></div></div></section><section className="bottom-shelves"><div><span className="section-kicker">Recently finished</span><div className="finished"><Cover book={books.redRising}/><p><b>Red Rising</b><br/><span>★★★★★ &nbsp; Your rating</span><br/><small>Finished 8 days ago</small></p></div></div></section></section></main>; }
function BookView({setView}:{setView:(v:View)=>void}) { const [saved,setSaved]=useState(false); return <main className="page-grid"><section className="content detail"><button className="back" onClick={()=>setView("home")}>← Back to my library</button><div className="detail-top"><Cover book={books.mistborn}/><div className="detail-copy"><span className="section-kicker">My copy · Paperback</span><h1>Mistborn:<br/>The Final Empire</h1><p className="author">Brandon Sanderson</p><div className="rating"><Star fill="currentColor" size={17}/><b>4.47</b><span>· 1.1m ratings</span></div><p className="description">For a thousand years, ash has fallen and the Lord Ruler has reigned. But a crew of the cleverest thieves in the city may have found a way to bring him down.</p><div className="detail-actions"><button className="ink-button">Reading now <ChevronRight size={16}/></button><button className={saved?"save-button saved":"save-button"} onClick={()=>setSaved(!saved)}>{saved?<Check size={16}/>:<Bookmark size={16}/>} {saved?"Saved to TBR":"Save for later"}</button></div></div><button className="dots" aria-label="More actions"><MoreHorizontal/></button></div><div className="detail-layout"><section className="personal-card"><div className="card-heading"><div><span className="section-kicker">This is yours</span><h2>My reading record</h2></div><button className="text-action">Edit</button></div><div className="record-grid"><div><small>STATUS</small><b><span className="reading-dot"/> Currently reading</b></div><div><small>PROGRESS</small><b>55% · Chapter 21</b></div><div><small>MY RATING</small><b className="soft">Not rated yet</b></div><div><small>WHERE I GOT IT</small><b>Owned · Paperback</b></div></div><div className="note-box"><span>MY NOTE</span><p>“The pieces are starting to click. I love how much is hiding in plain sight — especially the small moments between Vin and Kelsier.”</p><small>Updated yesterday</small></div></section><aside className="context-card"><span className="section-kicker">Part of your world</span><p>Because you loved <b>Red Rising</b> and fast-moving fantasy, we think you’ll want to keep this one close.</p><button onClick={()=>setView("recommendations")}>See what’s next <ArrowUpRight size={15}/></button></aside></div></section></main>; }
function Recommendation({setView}:{setView:(v:View)=>void}) { const [thinking,setThinking]=useState(true); const [added,setAdded]=useState(false); useEffect(()=>{if(!thinking)return;const id=setTimeout(()=>setThinking(false),1200);return()=>clearTimeout(id)},[thinking]); return <main className="page-grid"><section className="content recommendations"><div className="eyebrow"><Sparkles size={14}/> Your next great read</div><h1>Something picked <em>just</em> for you.</h1>{thinking?<div className="thinking" role="status" aria-label="Building a recommendation from your library"><div className="signal-stream"><span className="signal-chip chip-a">Mistborn</span><span className="signal-chip chip-b">Red Rising</span><span className="signal-chip chip-c">Babel</span><div className="signal-core"><Sparkles size={24}/></div></div><span className="thinking-status">Tracing the threads in your library</span></div>:<div className="rec-reveal"><section className="feature-rec"><div className="rec-cover"><Cover book={books.will}/><span>YOUR NEXT READ</span></div><div className="rec-copy"><span className="section-kicker">A thoughtful recommendation</span><h2>The Will of the Many</h2><p className="author">James Islington</p><p className="rec-reason">You wrote that <i>Mistborn</i> won you over with its mounting momentum and a magic system that slowly reveals its logic. You also rated <i>Red Rising</i> five stars.</p><p className="rec-reason">This has the same forward pull: a young outsider, a strict power system to uncover, and a mystery that keeps opening into something larger.</p><div className="traits"><span>Fast-moving</span><span>Power system</span><span>Central mystery</span></div><div className="detail-actions"><button className={added?"ink-button added":"ink-button"} onClick={()=>setAdded(!added)}>{added?<Check size={16}/>:<Plus size={16}/>} {added?"Added to your TBR":"Add to my TBR"}</button><button className="save-button">Not for me</button></div></div></section><section className="why-card"><span className="section-kicker">Why this, now?</span><div><span className="why-number">01</span><p><b>You like momentum.</b><br/>Your highest-rated recent reads get moving early and never really let go.</p></div><div><span className="why-number">02</span><p><b>You follow the rules.</b><br/>You’re drawn to worlds whose systems become more interesting the deeper you go.</p></div><button onClick={()=>setThinking(true)}>Find another angle <ChevronRight size={15}/></button></section></div>}</section></main>; }
export default function Home() { const [view,setView]=useState<View>("home"); return <><Nav view={view} setView={setView}/>{view==="home"?<HomeView setView={setView}/>:view==="book"?<BookView setView={setView}/>:<Recommendation setView={setView}/>}</>; }
