"use client";

import { useEffect, useState } from "react";
import { ArrowUpRight, Bookmark, Check, ChevronRight, Clock3, Heart, Home as HomeIcon, Library, MoreHorizontal, Plus, Sparkles, Star } from "lucide-react";

type View = "home" | "book" | "recommendations";
const books = {
  mistborn: { title: "Mistborn: The Final Empire", author: "Brandon Sanderson", image: "https://covers.openlibrary.org/b/isbn/9780765311788-L.jpg" },
  babel: { title: "Babel", author: "R. F. Kuang", image: "https://covers.openlibrary.org/b/isbn/9780063021426-L.jpg" },
  redRising: { title: "Red Rising", author: "Pierce Brown", image: "https://covers.openlibrary.org/b/isbn/9780345539786-L.jpg" },
  will: { title: "The Will of the Many", author: "James Islington", image: "https://covers.openlibrary.org/b/isbn/9781982141175-L.jpg" },
  priory: { title: "The Priory of the Orange Tree", author: "Samantha Shannon", image: "https://covers.openlibrary.org/b/isbn/9781635570298-L.jpg" },
};
type Book = typeof books.mistborn;
function Cover({ book, className = "" }: {book: Book; className?: string}) { return <img className={`book-cover ${className}`} src={book.image} alt={`Cover of ${book.title}`} />; }
function Nav({view,setView}:{view:View;setView:(v:View)=>void}) { return <header className="topbar"><button className="brand" onClick={()=>setView("home")}><span>l</span> Lumen</button><nav><button className={view==="home"?"active":""} onClick={()=>setView("home")}><HomeIcon size={16}/> My library</button><button className={view==="recommendations"?"active":""} onClick={()=>setView("recommendations")}><Sparkles size={16}/> For you</button></nav><button className="avatar" aria-label="Open profile">DA</button></header>; }
function Rail({view,setView}:{view:View;setView:(v:View)=>void}) { return <aside className="rail"><button className={view==="home"?"rail-active":""} onClick={()=>setView("home")}><Library size={18}/> Library</button><button onClick={()=>setView("recommendations")}><Sparkles size={18}/> Discover</button><div className="rail-label">Your shelves</div><button><Clock3 size={17}/> Reading now <b>1</b></button><button><Bookmark size={17}/> Up next <b>12</b></button><button><Check size={17}/> Read this year <b>18</b></button><button><Heart size={17}/> Want to buy <b>9</b></button></aside>; }
function MiniBook({book,onClick}:{book:Book;onClick?:()=>void}) { return <button className="mini-book" onClick={onClick}><Cover book={book}/><span>{book.title}</span><small>{book.author}</small></button>; }
function HomeView({setView}:{setView:(v:View)=>void}) { return <main className="page-grid"><Rail view="home" setView={setView}/><section className="content"><div className="eyebrow"><span/> Your reading life</div><div className="home-heading"><div><h1>Good morning, Dan.</h1><p>Your books, your pace, your next great read.</p></div><button className="quiet-button"><Plus size={17}/> Add a book</button></div><section className="now-card"><div className="now-art"><Cover book={books.mistborn}/></div><div className="now-info"><span className="section-kicker">Continue reading</span><h2>Mistborn: The Final Empire</h2><p>Brandon Sanderson</p><div className="progress-row"><div><i/></div><span>Chapter 21 of 38</span></div><button className="ink-button" onClick={()=>setView("book")}>Open my book <ArrowUpRight size={16}/></button></div><div className="now-note"><span>YOUR NOTE</span><p>“The pieces are starting to click. I love how much is hiding in plain sight.”</p><small>Added yesterday</small></div></section><section className="shelf-section"><div className="section-title"><div><span className="section-kicker">Your next few</span><h2>Ready when you are</h2></div><button>View TBR <ChevronRight size={15}/></button></div><div className="book-row"><MiniBook book={books.babel}/><MiniBook book={books.priory}/><MiniBook book={books.will} onClick={()=>setView("recommendations")}/><div className="more-card"><span>12</span><small>more books<br/>waiting for you</small></div></div></section><section className="bottom-shelves"><div><span className="section-kicker">Recently finished</span><div className="finished"><Cover book={books.redRising}/><p><b>Red Rising</b><br/><span>★★★★★ &nbsp; Your rating</span><br/><small>Finished 8 days ago</small></p></div></div><button className="taste-card" onClick={()=>setView("recommendations")}><Sparkles size={19}/><span>Made for your taste</span><p>There’s a book waiting that connects the dots between your recent favorites.</p><strong>See your recommendation <ArrowUpRight size={16}/></strong></button></section></section></main>; }
function BookView({setView}:{setView:(v:View)=>void}) { const [saved,setSaved]=useState(false); return <main className="page-grid"><Rail view="book" setView={setView}/><section className="content detail"><button className="back" onClick={()=>setView("home")}>← Back to my library</button><div className="detail-top"><Cover book={books.mistborn}/><div className="detail-copy"><span className="section-kicker">My copy · Paperback</span><h1>Mistborn:<br/>The Final Empire</h1><p className="author">Brandon Sanderson</p><div className="rating"><Star fill="currentColor" size={17}/><b>4.47</b><span>· 1.1m ratings</span></div><p className="description">For a thousand years, ash has fallen and the Lord Ruler has reigned. But a crew of the cleverest thieves in the city may have found a way to bring him down.</p><div className="detail-actions"><button className="ink-button">Reading now <ChevronRight size={16}/></button><button className={saved?"save-button saved":"save-button"} onClick={()=>setSaved(!saved)}>{saved?<Check size={16}/>:<Bookmark size={16}/>} {saved?"Saved to TBR":"Save for later"}</button></div></div><button className="dots" aria-label="More actions"><MoreHorizontal/></button></div><div className="detail-layout"><section className="personal-card"><div className="card-heading"><div><span className="section-kicker">This is yours</span><h2>My reading record</h2></div><button className="text-action">Edit</button></div><div className="record-grid"><div><small>STATUS</small><b><span className="reading-dot"/> Currently reading</b></div><div><small>PROGRESS</small><b>55% · Chapter 21</b></div><div><small>MY RATING</small><b className="soft">Not rated yet</b></div><div><small>WHERE I GOT IT</small><b>Owned · Paperback</b></div></div><div className="note-box"><span>MY NOTE</span><p>“The pieces are starting to click. I love how much is hiding in plain sight — especially the small moments between Vin and Kelsier.”</p><small>Updated yesterday</small></div></section><aside className="context-card"><span className="section-kicker">Part of your world</span><p>Because you loved <b>Red Rising</b> and fast-moving fantasy, we think you’ll want to keep this one close.</p><button onClick={()=>setView("recommendations")}>See what’s next <ArrowUpRight size={15}/></button></aside></div></section></main>; }
function Recommendation({setView}:{setView:(v:View)=>void}) { const [thinking,setThinking]=useState(true); const [added,setAdded]=useState(false); useEffect(()=>{if(!thinking)return;const id=setTimeout(()=>setThinking(false),1200);return()=>clearTimeout(id)},[thinking]); return <main className="page-grid"><Rail view="recommendations" setView={setView}/><section className="content recommendations"><div className="eyebrow"><Sparkles size={14}/> Your next great read</div><h1>Something picked <em>just</em> for you.</h1><p className="rec-lede">Not a list of what’s popular. A considered read based on the stories you’ve made yours.</p>{thinking?<div className="thinking"><div className="orbit"><Sparkles size={26}/></div><span>Looking through the books that stayed with you…</span><small>Connecting your ratings, notes, and recent reads</small></div>:<div className="rec-reveal"><section className="feature-rec"><div className="rec-cover"><Cover book={books.will}/><span>YOUR NEXT READ</span></div><div className="rec-copy"><span className="section-kicker">A thoughtful recommendation</span><h2>The Will of the Many</h2><p className="author">James Islington</p><p className="rec-reason">You wrote that <i>Mistborn</i> won you over with its mounting momentum and a magic system that slowly reveals its logic. You also rated <i>Red Rising</i> five stars.</p><p className="rec-reason">This has the same forward pull: a young outsider, a strict power system to uncover, and a mystery that keeps opening into something larger.</p><div className="traits"><span>Fast-moving</span><span>Power system</span><span>Central mystery</span></div><div className="detail-actions"><button className={added?"ink-button added":"ink-button"} onClick={()=>setAdded(!added)}>{added?<Check size={16}/>:<Plus size={16}/>} {added?"Added to your TBR":"Add to my TBR"}</button><button className="save-button">Not for me</button></div></div></section><section className="why-card"><span className="section-kicker">Why this, now?</span><div><span className="why-number">01</span><p><b>You like momentum.</b><br/>Your highest-rated recent reads get moving early and never really let go.</p></div><div><span className="why-number">02</span><p><b>You follow the rules.</b><br/>You’re drawn to worlds whose systems become more interesting the deeper you go.</p></div><button onClick={()=>setThinking(true)}>Find another angle <ChevronRight size={15}/></button></section></div>}</section></main>; }
export default function Home() { const [view,setView]=useState<View>("home"); return <><Nav view={view} setView={setView}/>{view==="home"?<HomeView setView={setView}/>:view==="book"?<BookView setView={setView}/>:<Recommendation setView={setView}/>}</>; }
